sudo: false
language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: make test
